spring:
  profiles:
    active: local

logging:
  level:
    root: INFO
    org.package: INFO
    io:
      awspring:
        cloud: debug

server:
  port: 8080
  address: 0.0.0.0


---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: videoStreamingDB
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  services:
    path: /api/youtube
  cloud:
    aws:
      profile: default
      region: ap-south-1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://karthick-v.us.auth0.com/
          audience: https://api.avkarthick.in  
  auth:
    user-info-endpoint: https://karthick-v.us.auth0.com/userinfo
  aws-s3:
    bucket-name: amzn-s3-videostreaming-app-bucket

---
spring:
  config:
    activate:
      on-profile: cloud
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: videoStreamingDB
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  services:
    path: /api/youtube
  cloud:
    aws:
      region: ap-south-1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://karthick-v.us.auth0.com/
          audience: https://api.avkarthick.in
  auth:
    user-info-endpoint: https://karthick-v.us.auth0.com/userinfo
  aws-s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}





    


