spring:
  profiles:
    active: dev

logging:
 level:
  io:
   awspring:
    cloud: debug

server:
  port: 8081
  address: 0.0.0.0
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: videoStreamingDB
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  services:
    path: /api/youtube
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ap-south-1
      stack:
        auto: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://karthick-v.us.auth0.com/
  auth:
    user-info-endpoint: https://karthick-v.us.auth0.com/userinfo

    


